version: '2'
services:
    affiliate-app:
        image: affiliate
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:sqlserver://affiliate-mssql:1433;database=affiliate
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    affiliate-mssql:
        extends:
            file: mssql.yml
            service: affiliate-mssql
